# Generated by Django 4.1.2 on 2023-06-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='id_categoria', default=0, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('rating', models.IntegerField()),
                ('editorial', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('autor', models.CharField(max_length=60)),
                ('formato', models.CharField(max_length=60)),
                ('tamanio', models.CharField(max_length=20)),
                ('paginas', models.IntegerField()),
                ('descripcion', models.TextField(max_length=500)),
                ('pic1', models.ImageField(null=True, upload_to='')),
                ('pic2', models.ImageField(null=True, upload_to='')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='Mangas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('constrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mangas.manga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mangas.usuario')),
            ],
        ),
    ]
