# Generated by Django 4.1.2 on 2023-06-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mangas', '0002_alter_manga_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='pic1',
            field=models.ImageField(null=True, upload_to='mangas'),
        ),
    ]
