# Generated by Django 4.1.2 on 2023-06-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mangas', '0003_alter_manga_pic1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='pic2',
            field=models.ImageField(null=True, upload_to='mangas'),
        ),
    ]
