# Generated by Django 4.1.2 on 2023-06-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField()),
                ('nombre_categoria', models.CharField(default='Josei', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('rating', models.IntegerField()),
                ('editorial', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('autor', models.CharField(max_length=60)),
                ('formato', models.CharField(max_length=60)),
                ('tamanio', models.CharField(max_length=20)),
                ('paginas', models.IntegerField()),
                ('descripcion', models.TextField(max_length=1000)),
                ('pic1', models.ImageField(null=True, upload_to='mangas')),
                ('pic2', models.ImageField(null=True, upload_to='mangas')),
                ('nombre_categoria', models.ForeignKey(db_column='nombre_categoria', default='Josei', on_delete=django.db.models.deletion.CASCADE, to='Mangas.categoria')),
            ],
        ),
    ]
